[features]
seeds = false
skip-lint = false
[programs.devnet]
nft = "Hu1PQ3PcZynx7hJVdtxVQkeUz1bFNbVeFVUSYE164zex"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/muusshh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
